### ISSUE TITLE
Error with exporter

### ISSUE THREAD

**Issue by typicalaimster** [tcivie/meshtastic-metrics-exporter#30]
**Describe the bug**
Error in the logs and the exporter not starting

**To Reproduce**
1. Start things with docker-compose up --build

**Expected behavior**
For it to work

**Additional context**

```
exporter-1    | Traceback (most recent call last):

exporter-1    |   File "/app/main.py", line 8, in <module>

exporter-1    |     from constants import callback_api_version_map, protocol_map

exporter-1    | ModuleNotFoundError: No module named 'constants'

exporter-1 exited with code 1
```

**Comment by tcivie** [comment]
@typicalaimster Thank's for the feedback, looks like I overlook that when I tested my last changes locally. I Have added some test to avoid similar issues in the future :)

**Comment by typicalaimster** [comment]
Verified working, thanks!
