### ISSUE TITLE
Issues with docker-compose.yml

### ISSUE THREAD

**Issue by bob109** [tcivie/meshtastic-metrics-exporter#33]
When I issue the command ` docker-compose up --build` I get the following output.

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'grafana'
Unsupported config option for volumes: 'grafana_data'
Unsupported config option for networks: 'mesh-bridge'
```
Running it a second time I get the following
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for volumes: 'grafana_data'
Unsupported config option for networks: 'mesh-bridge'
Unsupported config option for services: 'prometheus'
```
A third time comes up different again.
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services: 'grafana'
Unsupported config option for networks: 'mesh-bridge'
Unsupported config option for volumes: 'postgres_data'
```

This is on a CentOS Linux server that I currently have other containers running on. 
`docker version` returns the following
```
Client: Docker Engine - Community
 Version:           26.0.0
 API version:       1.45
 Go version:        go1.21.8
 Git commit:        2ae903e
 Built:             Wed Mar 20 15:21:09 2024
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          26.0.0
  API version:      1.45 (minimum version 1.24)
  Go version:       go1.21.8
  Git commit:       8b79278
  Built:            Wed Mar 20 15:20:06 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by tcivie** [comment]
Hey @bob109 , can you please specify your docker-compose version by running `docker-compose version`?

**Comment by bob109** [comment]
That was it! Thank you! I didn't realize the version in the CentOS repo was that old (1.18.0, build 8dd22a9).  I uninstalled the old version and went right to the docker-compose github repo for the latest.  Seems to work like a charm now. Thank you! 

BTW.  After the build I do a docker-compose up and I don't get returned to a prompt.  Previous containers work in the background with no std-out.  I'm getting what looks like logging output from the containers.  Is this something I'm doing wrong here, or should I open another issue?

Thanks again!

**Comment by tcivie** [comment]
> That was it! Thank you! I didn't realize the version in the CentOS repo was that old (1.18.0, build 8dd22a9). I uninstalled the old version and went right to the docker-compose github repo for the latest. Seems to work like a charm now. Thank you!
> 
> BTW. After the build I do a docker-compose up and I don't get returned to a prompt. Previous containers work in the background with no std-out. I'm getting what looks like logging output from the containers. Is this something I'm doing wrong here, or should I open another issue?
> 
> Thanks again!

Hey @bob109 , I'm glad to hear you solved this :)

About your question, I think what you are looking for is the flag `-d` which should "detach" the process and get you right back to your prompt. I usually just do this: `docker compose up -d ` but you can look up fuhrther on the docker documentation for any options.

This is a more related question to the docker team so I'll close this ticket as it looks like everything is working as expected.
