### ISSUE TITLE
Persistent data in node graph

### ISSUE THREAD

**Issue by noon92** [tcivie/meshtastic-metrics-exporter#52]
old data is persistent. I think nodes should be removed from the graph when neighborinfo doesn't arrive for, say, 12 hours at most. if data is persistent, old data basically sticks around forever if a node goes offline, leading to a very misleading graph.

**Comment by Talie5in** [comment]
Additionally, I think it would be nice to remove nodes with no neighbours and "unknowns" from the Node Graph

**Comment by Talie5in** [comment]
Oh winner!

Thanks!

**Comment by tcivie** [comment]
Hey, so I'll add add expiration of 12 hours to the Postgres Database for the neighbourinfo data. It's not the best approach due to customizability issues but I believe if a node hasnt sent out any neighbourinfo data in 12 hours then it's probably irrelevant.
