### ISSUE TITLE
Another way to determine MQTT as Online/Offiline (meshtastic/firmware/pull/4305)

### ISSUE THREAD

**Issue by Talie5in** [tcivie/meshtastic-metrics-exporter#55]
https://github.com/meshtastic/firmware/pull/4305 has changed/removed the status topic from MQTT which now stops the ability to see if the MQTT is Online or Offline in the dashboards (regardless of using a private MQTT broker)

Is there another method that can be used to determine the status?

**Comment by tcivie** [comment]
Hey @Talie5in , I'm not aware of any in particular. I have used the recomendation the Meshtastic has in their documentation to work with that. -> https://meshtastic.org/docs/software/integrations/mqtt/#mqtt-topics

I don't think you can know for sure if the packet the exporter read can be identified if it came from the Node connected to the MQTT server or if it's just packet that is traveling around.

I'll close this issue for now as it's not really an issue and it has to do with the restrictions the public MQTT server has.
