### ISSUE TITLE
Created and Updated fields are always the Same

### ISSUE THREAD

**Issue by Talie5in** [tcivie/meshtastic-metrics-exporter#60]
Appears the "Created Time" and "Updated time" for nodelist is always the same.

![image](https://github.com/user-attachments/assets/32ca6f3e-3dd4-4f15-81ff-c92ef385d83e)

**Comment by tcivie** [comment]
Hey @Talie5in when the node first registered on the DB the values for created and last updated are the same. 

If the exporter would notice another packet from any existing node then it would update the 'last updated' field.

**Comment by Talie5in** [comment]
This may be my bad assumption here, but changing a node name would count as an update?
If so, have tested this and "Updated" doesn't chnage, but the node details do update/display changes in Grafana.

**Comment by Talie5in** [comment]
@tcivie I do believe in bad assumptions, as I accept that it's possible to be wrong :)
