### ISSUE TITLE
List of active deployments

### ISSUE THREAD

**Issue by tb0hdan** [tcivie/meshtastic-metrics-exporter#70]
Hi,

Please list the Canadaverse dashboard: https://dash.mt.gt / guest:guest

It can be a good showcase for this project

Thanks

**Comment by tcivie** [comment]
@tb0hdan Thanks for the contribution! I have added your dashboard to the README.md file :)

**Comment by HansvanMeer** [comment]
@tcivie Great job you've done! 

You can list this as Europe dashboard [https://meshtastic.hvm.nu] (https://meshtastic.hvm.nu).
No password is required.

It listen to EU868.
